name: Containerized Train CI/CD
run-name: Train CI/CD
on: [push]
env:
  CLUSTER: amineb-cluster
  CLUSTER_ZONE: europe-west1-b
jobs:
  BuildAndPushDockerImage:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            mbouzayeni/train-schedule:${{ github.sha }}
          cache-from: type=registry,ref=mbouzayeni/train-schedule:buildcache
          cache-to: type=registry,ref=mbouzayeni/train-schedule:buildcache,mode=max              
  DeployCanary:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: BuildAndPushDockerImage
    permissions:
     contents: 'read'
     id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/54598601140/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc'
          service_account: '54598601140-compute@developer.gserviceaccount.com'
          project_id: playground-s-11-19839254
          cleanup_credentials: false
      - name: Connect to GKE
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.CLUSTER }}
          location: ${{ env.CLUSTER_ZONE }}
      - name: Replace the variables in the kubernetes config file
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["./train-schedule-kube-canary.yml"]'
          tokenPrefix: __
          tokenSuffix: __
        env:
          DOCKER_IMAGE_NAME: mbouzayeni/train-schedule
          BUILD_NUMBER: ${{ github.sha }}
          CANARY_REPLICAS: 1

      - name: Deploy to the gke cluster
        run: kubectl apply -f train-schedule-kube-canary.yml
  SmokeTestsOnCanaryPods:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [BuildAndPushDockerImage, DeployCanary]
    steps:
      - name: Run Smoke Tests
        run: |
            response=$(curl -s -o /dev/null -w "%{http_code}"  http://35.195.20.210:30081/)
            if [[ $response != 200 ]]
              then
              echo "Smoke test against the canary deployment failed"
              exit 1
            else
              echo "The smoke tests were passed"  
            fi  
  DeleteCanaryDeployment:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && success() || failure()
    needs: [BuildAndPushDockerImage, DeployCanary, SmokeTestsOnCanaryPods]
    permissions:
     contents: 'read'
     id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/54598601140/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc'
          service_account: '54598601140-compute@developer.gserviceaccount.com'
          project_id: playground-s-11-19839254
      - name: Connect to GKE
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.CLUSTER }}
          location: ${{ env.CLUSTER_ZONE }}
      - name: Replace the variables in the kubernetes canary config file
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["./train-schedule-kube-canary.yml"]'
          tokenPrefix: __
          tokenSuffix: __
        env:
          DOCKER_IMAGE_NAME: mbouzayeni/train-schedule
          BUILD_NUMBER: ${{ github.sha }}
          CANARY_REPLICAS: 0
      - name: Delete the canary pods
        run: kubectl apply -f train-schedule-kube-canary.yml      

  DeployToKubernetesProduction:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [BuildAndPushDockerImage, DeployCanary, DeleteCanaryDeployment]
    environment: production
    permissions:
     contents: 'read'
     id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/54598601140/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc'
          service_account: '54598601140-compute@developer.gserviceaccount.com'
          project_id: playground-s-11-19839254
      - name: Connect to GKE
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.CLUSTER }}
          location: ${{ env.CLUSTER_ZONE }}
      - name: Replace the variables in the kubernetes config file
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["./train-schedule-kube.yml"]'
          tokenPrefix: __
          tokenSuffix: __
        env:
          DOCKER_IMAGE_NAME: mbouzayeni/train-schedule
          BUILD_NUMBER: ${{ github.sha }}
      - name: Deploy to production
        run: kubectl apply -f train-schedule-kube.yml